# Uncomment this line to define a global platform for your project
# platform : ios, '9.0'

target 'WildcatConnect' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WildcatConnect

  pod 'CocoaLumberjack'

  target 'WildcatConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WildcatConnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
